/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showConfirmDialog;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.table.DefaultTableModel;

/**
 *Główna klasa programu.
 * 
 * @author Konrad Stano i Paweł Szostak
 */
public class ss_main extends javax.swing.JFrame {

    public int n;
    private DefaultTableModel model;
    private CObliczenia Macierz;
    private final CPliki plik;
    
    /**
     * Creates new form ss_main, ss-skrót od StanoSzostak
     */
    public ss_main() {
        initComponents();
        plik = new CPliki();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        przegladaj = new javax.swing.JButton();
        wczytaj = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Lub podaj ilość równań i niewiadomych n:");

        jTextField1.setText("0");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nr równania", "Współczynniki"
            }
        ));
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(85);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(85);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(85);
        }

        jLabel2.setText("Oraz podaj współczynniki i wyrazy wolne odzielając średnikiem kolejne liczby (;).");

        jButton2.setText("Oblicz");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ObliczActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nr X'a", "Wartosc"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jLabel3.setText("Wczytaj dane:");

        jTextField2.setText("Wybierz plik");

        przegladaj.setText("Przeglądaj");
        przegladaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                przegladajActionPerformed(evt);
            }
        });

        wczytaj.setText("Wczytaj");
        wczytaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wczytajActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 0, 0));
        jButton3.setText("EXIT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(274, 274, 274)
                                .addComponent(przegladaj)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(wczytaj))
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(przegladaj)
                            .addComponent(wczytaj)))
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    /**
     * Po wpisaniu liczby do jTextField1 i wciśnięciu entera ukazuje nam się 
     * tableka jTable1 do wprowadzania danych
     * 
     * @param evt 
     */
    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        try
        {
            n = Integer.parseInt(jTextField1.getText());
        }
        catch(NumberFormatException e) 
        { 
            showMessageDialog(null,"Wpisałeś inny znak niż liczba! Popraw się");
        }
        if(n<0 && n==(int)n)
        {
            showMessageDialog(null, "n nie może być ujemne! Podaj nowe n.");
        }
        else
        {
            String m[] = {"Nr równania", "Współczynniki"};
            model = new DefaultTableModel(null,m);
            jTable1.setModel(model);
            jTable1.putClientProperty("terminateEditOnFocusLost", Boolean.TRUE);
            Macierz = new CObliczenia(n);
            Macierz.PokazDane(jTable1, model);
        }
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * Po wpisaniu liczby do jTextField1 i wciśnięciu 'OK' ukazuje nam się 
     * tableka jTable1 do wprowadzania danych
     * 
     * @param evt 
     */
    private void jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActionPerformed
        try
        {
            n = Integer.parseInt(jTextField1.getText());
        }
        catch(NumberFormatException e) 
        { 
            showMessageDialog(null,"Wpisałeś inny znak niż liczba! Popraw się");
        }
        if(n<0 && n==(int)n)
        {
            showMessageDialog(null, "n nie może być ujemne! Podaj nowe n.");
        }
        else
        {
            String m[] = {"Nr równania", "Współczynniki"};
            model = new DefaultTableModel(null,m);
            jTable1.setModel(model);
            jTable1.putClientProperty("terminateEditOnFocusLost", Boolean.TRUE);
            Macierz = new CObliczenia(n);
            Macierz.PokazDane(jTable1, model);
        }
    }//GEN-LAST:event_jButtonActionPerformed

    /**
     * Po wciśnięciu przycisku 'Oblicz' dokonywane są wszystkie obliczenia na
     * podstawie danych z jTable1, a wyniki są wyświetlane w jTable2.
     * 
     * @param evt 
     */
    private void ObliczActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ObliczActionPerformed
        if(n>0)
        {
            String m[] = {"Nr X'a", "Wartość"};
            model = new DefaultTableModel(null,m);
            jTable2.setModel(model);
            jTable2.putClientProperty("terminateEditOnFocusLost", Boolean.TRUE);
            Macierz.PrzypiszDane(jTable1);
            if(Macierz.WyznaczWartosci()==2)
            {
                Macierz.PrzypiszRozw(jTable2, model);
            }
            else if(Macierz.WyznaczWartosci()==1)
            {
                showMessageDialog(null, "Dzielenie przez zero! Brak rozwiązań!");
            }
        }
        else
        {
            showMessageDialog(null, "Brak danych do wykonania obliczeń!");
        }
    }//GEN-LAST:event_ObliczActionPerformed

    /**
     * Po wciśnięciu przycisku 'Przeglądaj' wyskakuje nam okienko dzięki któremu
     * możemy wybrać plik z dysku komputera.
     * 
     * @param evt 
     */
    private void przegladajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_przegladajActionPerformed
        //plik = new CPliki();
        try {
            plik.Szukaj(jTextField2);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ss_main.class.getName()).log(Level.SEVERE, null, ex);
            showMessageDialog(null, "Brak pliku!");
        }
    }//GEN-LAST:event_przegladajActionPerformed

    /**
     * Po wciśnięciu przycisku 'Wczytaj' wczytane zostaną dane z ówcześniej
     * wybranego pliku i wyświetlone w jTable1.
     * @param evt 
     */
    private void wczytajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wczytajActionPerformed
        String m[] = {"Nr równania", "Współczynniki"};
        model = new DefaultTableModel(null,m);
        jTable1.setModel(model);
        jTable1.putClientProperty("terminateEditOnFocusLost", Boolean.TRUE);
        try {
            plik.Wczytaj(jTable1, model, jTextField2);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ss_main.class.getName()).log(Level.SEVERE, null, ex);
            showMessageDialog(null, "Brak takiego pliku!");
        }
        n=plik.ilosc();
        Macierz = new CObliczenia(n);
    }//GEN-LAST:event_wczytajActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int dialogResult = showConfirmDialog (null, "Czy na pewno chcesz wyjść?");
        if(dialogResult == JOptionPane.YES_OPTION)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ss_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ss_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ss_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ss_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ss_main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    public javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton przegladaj;
    private javax.swing.JButton wczytaj;
    // End of variables declaration//GEN-END:variables
}
